### ISSUE TITLE
Scanner.emitIdOrKeyword map.getOrElse generating anonymous fn garbage

### ISSUE THREAD

**Issue by rorygraves** [twitter/reasonable-scala#31]
Profiling compiles:
```val token = keywords.getOrElse(lexeme, ID)```
generates an anonymous function for the default value part (AbstractFunction0).  It accounts for 1/3 of all Function0 instances created and is high on the garbage stakes.

I tried some simple stuff to get rid of the anon function and failed (replacing with get() effectively replaces it with an Some().  

Switching the tokens map to a j.u.Map would solve it (but ugly)

**Comment by xeno-by** [comment]
Switched to j.u.HashMap, got some nice performance improvements: https://github.com/twitter/reasonable-scala/pull/45/commits/200b1b53ab1a55460bda0b707f0f5639ef8fb534.

**Comment by xeno-by** [comment]
Fixed in https://github.com/twitter/reasonable-scala/commit/13490ad4b9ce2c2e05ecc7839246c271b3c751da.
