### ISSUE TITLE
Upgrade to Scala Native 0.3.6

### ISSUE THREAD

**Issue by densh** [twitter/reasonable-scala#39]
0.3.5 includes a number of changes that improve performance of rsc. Here are some very rough numbers on first 20 iterations, before:

```
Time: 243822417 ns
Time: 174314736 ns
Time: 172057764 ns
Time: 180346046 ns
Time: 172030039 ns
Time: 173087314 ns
Time: 165330589 ns
Time: 164671580 ns
Time: 164822682 ns
Time: 165409924 ns
Time: 164684067 ns
Time: 164456743 ns
Time: 164551160 ns
Time: 164383594 ns
Time: 164386438 ns
Time: 164382765 ns
Time: 164515369 ns
Time: 165105908 ns
Time: 165113140 ns
Time: 164425373 ns
```

And after:

```
Time: 134191805 ns
Time: 104693424 ns
Time: 95394359 ns
Time: 93703848 ns
Time: 94290683 ns
Time: 94184145 ns
Time: 94216223 ns
Time: 94065560 ns
Time: 93797489 ns
Time: 93983223 ns
Time: 93736858 ns
Time: 93647207 ns
Time: 93837259 ns
Time: 94148113 ns
Time: 94109868 ns
Time: 93244565 ns
Time: 93401882 ns
Time: 93801207 ns
Time: 92924482 ns
Time: 93191116 ns
```

**Update**: [0.3.6](https://github.com/scala-native/scala-native/releases/tag/v0.3.6) supersedes 0.3.5 due to regression in sbt testing integration.

**Comment by rorygraves** [comment]
wow!

**Comment by densh** [comment]
@xeno-by 

Here are the things that made the difference:

1. GC grows heap more aggressively. This improves the first iteration performance. 

2. `java.util.HashMap` was based on `scala.mutable.Map` before, we swap for `scala.mutable.AnyRefMap` instead. Generally, using java collections is not always the best idea performance-wise on Native as those are meant for compatibility, not for best performance. 

3. CHA didn't devirtualize trait methods with a single known implementation, this hurt a lot as you seem to have quite a few min-cakes everywhere (e.g. parser.)

**Comment by xeno-by** [comment]
Fixed in https://github.com/twitter/reasonable-scala/pull/41.
